In [3]:
import tensorflow as tf
from keras.preprocessing import image
import numpy as np
import keras
from keras import Model
import time
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import Conv3D

fileName = "Trump.jpg"



# Global MobileNets model
mobile = keras.applications.mobilenet.MobileNet(weights="imagenet")
model = Model(mobile.input, mobile.layers[80].output)

/home/nikhil/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
for layer in model.layers:
    print(layer)
    
layer78 = model.layers[78]
W = np.array(layer78.get_weights())

print("\n\n Weight Size")
print(W.shape)



 Weight Size
(1, 1, 1, 512, 1024)


In [5]:
def write_to_file_weights_layer_TwentyFive(fileName, W):
    fTemp = open(fileName, "w")
    for i in range(1):
        for j in range(1):
            for k in range(1024):
                for l in range(512):
                    fTemp.write(str(W[i][j][l][k]) + "\n")
    fTemp.close()


In [6]:
"""for layer in model.layers:
    print(layer)
"""
    
layer78 = model.layers[78]
W = np.array(layer78.get_weights())
print(W.shape)

W = layer78.get_weights()[0]
write_to_file_weights_layer_TwentyFive("data/TwentyFiveLayer/weightsNorm.txt", W)

W[:,:,:,:] = 1
write_to_file_weights_layer_TwentyFive("data/TwentyFiveLayer/weightsSet1.txt", W)

(1, 1, 1, 512, 1024)


In [5]:
import math as m
layer79 = model.layers[79]
W = np.array(layer79.get_weights())
print(W.shape)

batchNorm = model.layers[79].get_weights()

fMean = open("data/TwentyFiveLayer/TwentyFive_Layer_Mean.txt", "w")
fSD = open("data/TwentyFiveLayer/TwentyFive_Layer_StanDev.txt", "w")
fGamma = open("data/TwentyFiveLayer/TwentyFive_Layer_Gamma.txt", "w")
fBeta = open("data/TwentyFiveLayer/TwentyFive_Layer_Beta.txt", "w")


for i in range(len(batchNorm[0])):
    fGamma.write(str(float(batchNorm[0][i])) + "\n")

for i in range(len(batchNorm[1])):
    fBeta.write(str(float(batchNorm[1][i])) + "\n")

for i in range(len(batchNorm[2])):
    fMean.write(str(float(batchNorm[2][i])) + "\n")

for i in range(len(batchNorm[3])):
    # The Value for Epsilon is assumed to be 0.001 in this implementation
    fSD.write(str(m.sqrt(float(batchNorm[3][i]) + 0.001)) + "\n")


print(batchNorm[0])
print(batchNorm[1])
print(batchNorm[2])
print(batchNorm[3])

fMean.close()
fSD.close()
fGamma.close()
fBeta.close()


(4, 1024)
[1.6656146 1.3925942 1.271013  ... 1.1250055 1.0047609 0.8270665]
[-1.4405429 -1.1654054  0.95993   ... -0.6182911 -0.8993718  0.9665248]
[ 0.13638562  0.6913891   0.42542782 ... -0.08673581 -0.9567772
 -0.47628996]
[0.37522984 0.44892654 0.36006913 ... 1.0100319  0.40744388 0.16686559]


In [6]:
def checkFile_TwentyFiveLayer():
    fExp = open('data/TwentyFiveLayer/TwentyFive_Layer_Output.txt', 'r')
    fAct = open('data/TwentyFiveLayer/output.txt', 'r')
    
    cExp = fExp.readlines()
    cAct = fAct.readlines()
    counter = 0
    for i in range(len(cExp)):
         if int(round(float(cAct[i].strip()))) != int(round(float(cExp[i].strip()))):
            counter += 1
            if(counter < 30):
                print(str(cAct[i].strip()) + "--->" + str(cExp[i].strip()))
            
        
    print("Number of mismatch - " + str(counter))
    
    fExp.close()
    fAct.close()
    
        

In [2]:
checkFile_TwentyFiveLayer()

Number of mismatch - 0
